### ISSUE TITLE
MQTT or other way to integrate with HA, add cheap PH & TDS sensor.

### ISSUE THREAD

**Issue by phantomse** [CelliesProjects/aquacontrol32#31]
I'm interested in doing the same project but adding PH & TDS sensor for short periods and integrating it with Home Assistant in one way or another. With Tasmota/ESPHome/EspEasy I didn't have good progress.
Ex: 
https://www.aliexpress.com/item/32803578131.html?spm=a2g0o.detail.1000014.26.5c6d3ca0Wxwubd&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.13338.133222.0&scm_id=1007.13338.133222.0&scm-url=1007.13338.133222.0&pvid=759e65e9-64a6-4d37-8014-c67fddd57149

https://www.aliexpress.com/item/33018409143.html?spm=a2g0o.productlist.0.0.341d55b8n9RvVT&algo_pvid=1c0427b5-4019-4536-92bb-6f93a3ec6ba6&algo_expid=1c0427b5-4019-4536-92bb-6f93a3ec6ba6-32&btsid=cd7e0292-da68-4800-8f3d-bc8647a22d0f&ws_ab_test=searchweb0_0,searchweb201602_10,searchweb201603_55

**Comment by CelliesProjects** [comment]
Hi. Nice sensors. Any code to show?

-EDIT:
Just checked out HA and these are things (Alexa, Google) that I could live without.
