### ISSUE TITLE
Flashing Nodemcu

### ISSUE THREAD

**Issue by badstraw360** [CelliesProjects/aquacontrol32#38]
Hello, I'm trying to flash a Nodemcu but I'm getting this error even if I press the flash button on the board:

```
A fatal error occurred: Timed out waiting for packet header
```
What am I doing wrong? 

Thanks for putting so much effort into this project, I appreciate your help.

**Comment by CelliesProjects** [comment]
I usually get this error when the flash parameters are not correct or if the partition table is overwritten.
Maybe a full flash erase (before flashing the software) might solve your problem.
````bash
~/Arduino/hardware/espressif/esp32/tools/esptool.py --port /dev/ttyUSBx erase_flash
````
Change `/dev/tty/USBx` with the port your NodeMCU is connected to.

Or try a lower flash speed.

**Comment by badstraw360** [comment]
I did the full flash erase and lower flash speed but it doesn't work:

<img width="362" alt="Captura de Pantalla 2019-11-29 a la(s) 15 22 23" src="https://user-images.githubusercontent.com/34426306/69890854-d206c780-12bd-11ea-9d96-c361042a058d.png">

These are my settings: 

<img width="325" alt="Captura de Pantalla 2019-11-29 a la(s) 12 54 04" src="https://user-images.githubusercontent.com/34426306/69890857-d9c66c00-12bd-11ea-8001-64989ecf560f.png">


I tried to change the port where my nodeMCU is connected: 

```
~/arduino-1.8.10/arduino --board espressif:esp32:mhetesp32minikit --pref custom_DebugLevel=esp32_none --port /dev/cu.SLAB_USBtoUART  --pref upload.speed=921600 --preserve-temp-files --pref build.path=temp --pref build.partitions=default_ffat --pref build.flash_freq=80m -v --verify aquacontrol32.ino | grep  -e 'Using core' -e 'Using board' -e ' uses ' -e 'Using library' -e 'Compiling' -e 'Global'
rm gitTagVersion.h

```

and this:

```
~/arduino-1.8.10/arduino \
  --board espressif:esp32:mhetesp32minikit \
  --port /dev/cu.SLAB_USBtoUART \
  --preserve-temp-files \
  --pref build.path=temp \
  --pref upload.speed=921600 \
  --pref custom_DebugLevel=esp32_none \
  --pref build.partitions=default_ffat \
  --pref build.flash_freq=80m -v \
  --save-prefs \
  --upload aquacontrol32.ino \
```

But If I try to flash it with another code it works: 

<img width="267" alt="Captura de Pantalla 2019-11-29 a la(s) 13 30 29" src="https://user-images.githubusercontent.com/34426306/69890901-375ab880-12be-11ea-8b94-11e0696c811c.png">

So I think it has something to do with the settings ... 

So if I try again I get this error: 

<img width="813" alt="Captura de Pantalla 2019-11-29 a la(s) 16 00 14" src="https://user-images.githubusercontent.com/34426306/69891327-6a527b80-12c1-11ea-9c84-4b6aa340cbf8.png">


I would really appreciate your help. :) 

Thanks again.

**Comment by badstraw360** [comment]
I guess it's because the board is not ESP32... :( 

Is there a possibility to flash it with a ESP8266?

**Comment by CelliesProjects** [comment]
No that will not work.
