### ISSUE TITLE
Description off /webif/Readme.md Wrong

### ISSUE THREAD

**Issue by crazybanane** [CelliesProjects/aquacontrol32#49]
Hello,

i tried to make a Language change for the Html files and convert it to a same lookin file as your e.g. channels_htm_gz.h
But when i will compile it Arduino gives me failure on compiling. I think because i didnt gzipped it. But how to gzip it that it will work?
Or in what order i have to zip the file?

**Comment by CelliesProjects** [comment]
Hi @crazybanane 

Thanks for your interest in aquacontrol and pointing this out.

The explanation was very outdated.
I updated the description on preparing the web interface files. Hopefully this made it more clear.

[Updated explanation](https://github.com/CelliesProjects/aquacontrol32/tree/master/webif)

Feel free to reopen this issue if things dont work out or are unclear.

**Comment by crazybanane** [comment]
Thank you so much. It works just fine also on WIN11 with WSL and Kali Linux.
Is there a way that i can Upload German Language Website file inclusive Gzipped files here that anybody can use it?
Thank you so much for this great and Easy made Program

**Comment by CelliesProjects** [comment]
Yes, a PR with German language translation would be a nice addition.

I do have to think a bit about how to make it work in an easy and maintainable way.
I will report back if I have worked something out.

**Comment by crazybanane** [comment]
![german](https://user-images.githubusercontent.com/83918669/146676424-f459af02-1508-4e44-be7f-39186ebc5241.jpg)
I took the files from webif and translated it to german i can send you these if you want.

**Comment by CelliesProjects** [comment]
Yes, you can send them to <b>email removed</b>.
Remove space before and after @.

**Comment by crazybanane** [comment]
> Yes, you can send them to <b>email removed</b>.

On the way

**Comment by crazybanane** [comment]
Is it easy enough if you made in webif new folder with the language e.g.
webif>
         -de
         -en
         -esp........

and correct the code that the Compiler can search for it when language is set?
Or is it possible to upload the wbesite files via filemanager?

**Comment by CelliesProjects** [comment]
@crazybanane 
I might go for something like the first approach.
The second approach exposes the files through the filemanager and is imho not the best (rather ugly) solution.
For now I got multiple other fish to fry.

Thanks for your time and effort!
