### ISSUE TITLE
Arduino IDE verify problem

### ISSUE THREAD

**Issue by tibike32** [CelliesProjects/aquacontrol32#58]
**aquacontrol version:** 1.6.8

**Arduino IDE version:** 2.2.1

**ESP32 Arduino core version:** ESP32 DEV module

**The issue is:**
[replace this with a clear and concise desciption of the issue]

**Debug log:**
C:\aquacontrol32-1.6.8\aquacontrol32\webservertask.ino: In function 'bool setupMDNS(const char*)':
C:\aquacontrol32-1.6.8\aquacontrol32\webservertask.ino:673:49: error: cannot convert 'ip4_addr*' to 'esp_ip4_addr_t*' {aka 'esp_ip4_addr*'}
   esp_err_t res = mdns_query_a( hostname, 2000, &addr );
                                                 ^~~~~
In file included from C:\Users\tberenyi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\ESPmDNS\src/ESPmDNS.h:46,
                 from C:\aquacontrol32-1.6.8\aquacontrol32\aquacontrol32.ino:7:
C:\Users\tberenyi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11/tools/sdk/esp32/include/mdns/include/mdns.h:649:83: note:   initializing argument 3 of 'esp_err_t mdns_query_a(const char*, uint32_t, esp_ip4_addr_t*)'
 esp_err_t mdns_query_a(const char * host_name, uint32_t timeout, esp_ip4_addr_t * addr);
                                                                  ~~~~~~~~~~~~~~~~~^~~~

exit status 1

Compilation error: cannot convert 'ip4_addr*' to 'esp_ip4_addr_t*' {aka 'esp_ip4_addr*'}

**Additional information:**
I tried with another Arduino IDE version, but the problem is the same

**Comment by CelliesProjects** [comment]
@tibike32 I think this is because the ESP32 Arduino Core version you use is too recent.
The mdns lib changed quite a lot after I think 1.0.5 or 1.0.6.

Try compiling with [ESP Arduino Core 1.0.4](https://github.com/espressif/arduino-esp32/releases/tag/1.0.4) and see if that helps. 
Also take a look at which [libraries](https://github.com/CelliesProjects/aquacontrol32#libraries) need which version.
Most have changed considerably since 2019.

**Comment by tibike32** [comment]
If I use the Arduino IDE 1.8.12, still this error message. But I can't how use it the ESP Arduino Core 1.0.4 ?
I'm basic Arduino user.

**Comment by tibike32** [comment]
> @tibike32 I think this is because the ESP32 Arduino Core version you use is too recent. The mdns lib changed quite a lot after I think 1.0.5 or 1.0.6.
> 
> Try compiling with [ESP Arduino Core 1.0.4](https://github.com/espressif/arduino-esp32/releases/tag/1.0.4) and see if that helps. Also take a look at which [libraries](https://github.com/CelliesProjects/aquacontrol32#libraries) need which version. Most have changed considerably since 2019.

If I use the Arduino IDE 1.8.12, still this error message. But I can't how use it the ESP Arduino Core 1.0.4 ?
I'm basic Arduino user.
I check the libraries thats all ok.

**Comment by CelliesProjects** [comment]
Go to boards manager and search for esp32. 

Then click 1.0.4.

![boardman](https://github.com/CelliesProjects/aquacontrol32/assets/24290108/d7543d53-94ae-431b-baad-a2b28d690b3e)

**Comment by tibike32** [comment]
> Go to boards manager and search for esp32.
> 
> Then click 1.0.4.
> 
> I found it, but I just can't find it here 2.0.10 and 2.0.11

**Comment by tibike32** [comment]
> Go to boards manager and search for esp32.
> 
> Then click 1.0.4.
> 
> 

That's great !!! The verify is ok . 
Thank you the help !
Good night !

**Comment by CelliesProjects** [comment]
Closing this issue. Feel free to re-open if needed.
