### ISSUE TITLE
Dosing Pump integration

### ISSUE THREAD

**Issue by LZsolt75** [CelliesProjects/aquacontrol32#61]
I've been using aquacontrol32 v1.6.8 for two months now. 
Everything works according to my expectations, but it would be nice to have the possibility to use one or two dosing pumps that could also be operated by aquacontrol32. With adjustable start times and dosing durations.

**Comment by CelliesProjects** [comment]
Hi @LZsolt75 . 

The development of this version is more or less stopped. I am working on a new version that is not ready for release yet. 
So If you want to have extra features you will have to fork the project and add these yourself.
